sudo: require
language: generic

services:
  - docker

before_install:
  - docker build -t solarsnowfall/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true solarsnowfall/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-069138977486"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY