language: generic
sudo: require
services:
  - docker

before_install:
  - docker build -t solarsnowfall/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true solarsnowfall/docker-react npm run test